services:
  - type: web
    name: jobboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask db upgrade && gunicorn run:app
    healthCheckPath: /healthz
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
